@startuml
'https://plantuml.com/class-diagram
!theme vibrant
class Autenticazione {
  +email: String
  +password: String
}
Autenticazione "1" -- "1" Utente:AccessoUtente
Autenticazione "1" --- "1" Gestore:AccessoGestore
class Utente{
  +nome: String
  +cognome: String
  +dataNascita: Date
  +comunediNascita: String
  +sesso: sesso
  +codiceFiscale: String
}
note "{ Partial , Overlapping }" as N1
Utente ... N1
Operatore .. N1
Studente .. N1
class Sede {
  +città: String
  +via: String
  +civico: String
  +provincia: String
  +cap: Integer
}
class Gestore {
  +nome: String
  +descrizione: String
  +telefono: String
  +cod.Gestore: String
}
Gestore "*" - "1" Sede:Collocato
class Operatore{
  +cod.Operatore
}
class Studente{
  +cod.Studente
}
enum sesso{
M
F
}
Utente "1" -- "0..1" Operatore:EssereOperatore
Utente "1" -- "0..1" Studente:EssereStudente
Gestore "1" -- "0..*" Corso:Possiede
Corso "*" -- "*" Studente
Corso "*" - "1..*" Operatore:Gestiti
class Corso{
  +titolo: String
  +descrizione: String
  +iscrizioniMassime: double
  +tassoPresenzeMinime: float
  +cod.Corso: String
}
class AreaTematica{
  +Tipo
  +cod.AreaTematica
}
Corso "*" --- "1..*" AreaTematica:Appartengono
class Lezione{
  +titolo: String
  +descrizione: String
  +dataoraInizio: Timestamp
  +durata: Time
  +cod.Lezione: String
}
Corso "1" -- "1..*" Lezione:Svolto
(Corso, Studente) .. Iscritti
Lezione "*" -- "*" Studente:Prenotazione
class Iscritti{
+idonei: boolean
}
class Statistiche{
  presenzeMinime
  presenzeMassime
  presenzeMedie
  percentualeRiempimentoMedia
}
Corso "1" - "1" Statistiche:Associate
@enduml